---

- name: squid is present
  package:
    name: squid
    state: present

- name: squid config is present
  when: squid.external_config_file
  copy:
    src: "{{ playbook_dir }}/{{ squid.external_config_file }}"
    dest: /etc/squid/squid.conf
    backup: yes
  notify: reload squid

- name: squid config is present
  when: not squid.external_config_file
  template:
    src: squid.conf
    dest: /etc/squid/squid.conf
    backup: yes
  notify: reload squid

# in a heartbeat cluster
# heartbeat is starting
# the service
#
- name: squid is running
  when: squid.manage_service
  service:
    name: squid
    state: started

# ansible bug #350
# reload always starts service
# https://github.com/ansible/ansible-modules-core/issues/350
#
# gather info about the pid file
# and use it in reload handler
#
- name: check for pidfile
  stat:
    path: /var/run/squid.pid
  register: _squid_pidfile
  check_mode: false
